SELECT * FROM Customer;
SELECT * FROM Supplier;
SELECT * FROM Category;
SELECT * FROM Coupon;
SELECT * FROM Product;
SELECT * FROM Orders;
SELECT * FROM OrderItems;
SELECT * FROM Shipment;
SELECT * FROM Payment;